### ISSUE TITLE
Create BUILD instructions

### ISSUE THREAD

**Issue by louquillio** [webrtc/webrtc-org#4]
Write instructions for building the site and serving locally, dependencies, etc.

**Comment by x1ddos** [comment]
I think the instructions could be taken from https://help.github.com/articles/using-jekyll-with-pages/ since the site is based on github-pages.

**Comment by samdutton** [comment]
@crhym3 fyi

**Comment by xdumaine** [comment]
+1 this took me a while to even figure out that _it is_ jekyll since I'm not a ruby guy and haven't used jekyll.

**Comment by samdutton** [comment]
OK — I've done this: updated [README.md](https://github.com/webrtc/webrtc-org/blob/gh-pages/README.md) with instructions for updating or adding content, and for building the site.

I also added AUTHORS, CONTRIBUTING.md and LICENSE.md.

(I've pushed this directly rather than use a pull request — thought we'd better get this up as soon as possible.)

@louquillio PTAL

**Comment by louquillio** [comment]
I think this is reasonably good, given that we can't explain every little thing _and_ that GitHub users are often familiar with GitHub Pages and therefore Jekyll, Markdown, etc. Let's close it for now and adjust if there seems to be confusion.
