### ISSUE TITLE
Explain how to install ruby for local dev

### ISSUE THREAD

**Issue by x1ddos** [webrtc/webrtc-org#56]
Most likely in https://github.com/webrtc/webrtc-org#build-and-run-the-site-locally

**Comment by randomascii** [comment]
The build-and-run-the-site-locally should also start by mentioning that this is usually not necessary. The current setup makes it look like running the site locally is the next step after making a correction or update or adding a new page. In fact local testing is rarely needed.

This problem is particularly acute for developers making a tiny change. The "Make a correction or update" section mentions nothing about testing, and the obvious reading flow takes the developer to the over-kill solution of testing locally.

**Comment by louquillio** [comment]
See PR #61. It might be best to say nothing about ruby, gems, bundler, etc. Can turn into a real snarl, and is out of scope for occasional editors.

@samdutton

**Comment by samdutton** [comment]
+1

**Comment by sgeoGPS** [comment]
高大上的感觉！呵呵~

**Comment by KaptenJansson** [comment]
latest here?

**Comment by rantonysamy** [comment]
Issue could be closed IMHO.
